use nu_ansi_term::Color as AnsiColor;
use nu_protocol::{Span, Value};

/// Convert an ANSI color to its Nushell string representation
pub fn ansi_color_to_string(color: AnsiColor, span: Span) -> Value {
    match color {
        AnsiColor::Black => Value::string("black", span),
        AnsiColor::Red => Value::string("red", span),
        AnsiColor::Green => Value::string("green", span),
        AnsiColor::Yellow => Value::string("yellow", span),
        AnsiColor::Blue => Value::string("blue", span),
        AnsiColor::Purple => Value::string("purple", span),
        AnsiColor::Magenta => Value::string("magenta", span),
        AnsiColor::Cyan => Value::string("cyan", span),
        AnsiColor::White => Value::string("white", span),
        AnsiColor::DarkGray => Value::string("dark_gray", span),
        AnsiColor::LightRed => Value::string("light_red", span),
        AnsiColor::LightGreen => Value::string("light_green", span),
        AnsiColor::LightYellow => Value::string("light_yellow", span),
        AnsiColor::LightBlue => Value::string("light_blue", span),
        AnsiColor::LightPurple => Value::string("light_purple", span),
        AnsiColor::LightMagenta => Value::string("light_magenta", span),
        AnsiColor::LightCyan => Value::string("light_cyan", span),
        AnsiColor::LightGray => Value::string("light_gray", span),
        AnsiColor::Default => Value::string("default", span),
        AnsiColor::Fixed(n) => Value::string(xterm_256_name(n), span),
        AnsiColor::Rgb(r, g, b) => Value::string(format!("#{:02x}{:02x}{:02x}", r, g, b), span),
    }
}

/// Convert an ANSI style to a Nushell record representation
pub fn ansi_style_to_record(
    style: nu_ansi_term::Style,
    span: nu_protocol::Span,
) -> nu_protocol::Value {
    use nu_protocol::{Record, Value};

    let mut record = Record::new();

    // Handle foreground color
    if let Some(color) = style.foreground {
        record.insert("fg".to_string(), ansi_color_to_string(color, span));
    }

    // Handle background color
    if let Some(color) = style.background {
        record.insert("bg".to_string(), ansi_color_to_string(color, span));
    }

    // Handle attributes
    let mut attrs = Vec::new();
    if style.is_bold {
        attrs.push("b"); // bold
    }
    if style.is_dimmed {
        attrs.push("d"); // dimmed
    }
    if style.is_italic {
        attrs.push("i"); // italic
    }
    if style.is_underline {
        attrs.push("u"); // underline
    }
    if style.is_blink {
        attrs.push("bl"); // blink
    }
    if style.is_reverse {
        attrs.push("r"); // reverse
    }
    if style.is_hidden {
        attrs.push("h"); // hidden
    }
    if style.is_strikethrough {
        attrs.push("s"); // strikethrough
    }

    if !attrs.is_empty() {
        let attr_value = Value::string(attrs.join(""), span);
        record.insert("attr".to_string(), attr_value);
    }

    Value::record(record, span)
}

fn xterm_256_name(color_idx: u8) -> &'static str {
    match color_idx {
        0 => "xblack",
        1 => "maroon",
        2 => "xgreen",
        3 => "olive",
        4 => "navy",
        5 => "xpurplea",
        6 => "teal",
        7 => "silver",
        8 => "grey",
        9 => "xred",
        10 => "lime",
        11 => "xyellow",
        12 => "xblue",
        13 => "fuchsia",
        14 => "aqua",
        15 => "xwhite",
        16 => "grey0",
        17 => "navyblue",
        18 => "darkblue",
        19 => "blue3a",
        20 => "blue3b",
        21 => "blue1",
        22 => "darkgreen",
        23 => "deepskyblue4a",
        24 => "deepskyblue4b",
        25 => "deepskyblue4c",
        26 => "dodgerblue3",
        27 => "dodgerblue2",
        28 => "green4",
        29 => "springgreen4",
        30 => "turquoise4",
        31 => "deepskyblue3a",
        32 => "deepskyblue3b",
        33 => "dodgerblue1",
        34 => "green3a",
        35 => "springgreen3a",
        36 => "darkcyan",
        37 => "lightseagreen",
        38 => "deepskyblue2",
        39 => "deepskyblue1",
        40 => "green3b",
        41 => "springgreen3b",
        42 => "springgreen2a",
        43 => "cyan3",
        44 => "darkturquoise",
        45 => "turquoise2",
        46 => "green1",
        47 => "springgreen2b",
        48 => "springgreen1",
        49 => "mediumspringgreen",
        50 => "cyan2",
        51 => "cyan1",
        52 => "darkreda",
        53 => "deeppink4a",
        54 => "purple4a",
        55 => "purple4b",
        56 => "purple3",
        57 => "blueviolet",
        58 => "orange4a",
        59 => "grey37",
        60 => "mediumpurple4",
        61 => "slateblue3a",
        62 => "slateblue3b",
        63 => "royalblue1",
        64 => "chartreuse4",
        65 => "darkseagreen4a",
        66 => "paleturquoise4",
        67 => "steelblue",
        68 => "steelblue3",
        69 => "cornflowerblue",
        70 => "chartreuse3a",
        71 => "darkseagreen4b",
        72 => "cadetbluea",
        73 => "cadetblueb",
        74 => "skyblue3",
        75 => "steelblue1a",
        76 => "chartreuse3b",
        77 => "palegreen3a",
        78 => "seagreen3",
        79 => "aquamarine3",
        80 => "mediumturquoise",
        81 => "steelblue1b",
        82 => "chartreuse2a",
        83 => "seagreen2",
        84 => "seagreen1a",
        85 => "seagreen1b",
        86 => "aquamarine1a",
        87 => "darkslategray2",
        88 => "darkredb",
        89 => "deeppink4b",
        90 => "darkmagentaa",
        91 => "darkmagentab",
        92 => "darkvioleta",
        93 => "xpurpleb",
        94 => "orange4b",
        95 => "lightpink4",
        96 => "plum4",
        97 => "mediumpurple3a",
        98 => "mediumpurple3b",
        99 => "slateblue1",
        100 => "yellow4a",
        101 => "wheat4",
        102 => "grey53",
        103 => "lightslategrey",
        104 => "mediumpurple",
        105 => "lightslateblue",
        106 => "yellow4b",
        107 => "darkolivegreen3a",
        108 => "darkseagreen",
        109 => "lightskyblue3a",
        110 => "lightskyblue3b",
        111 => "skyblue2",
        112 => "chartreuse2b",
        113 => "darkolivegreen3b",
        114 => "palegreen3b",
        115 => "darkseagreen3a",
        116 => "darkslategray3",
        117 => "skyblue1",
        118 => "chartreuse1",
        119 => "lightgreena",
        120 => "lightgreenb",
        121 => "palegreen1a",
        122 => "aquamarine1b",
        123 => "darkslategray1",
        124 => "red3a",
        125 => "deeppink4c",
        126 => "mediumvioletred",
        127 => "magenta3",
        128 => "darkvioletb",
        129 => "purplec",
        130 => "darkorange3a",
        131 => "indianreda",
        132 => "hotpink3a",
        133 => "mediumorchid3",
        134 => "mediumorchid",
        135 => "mediumpurple2a",
        136 => "darkgoldenrod",
        137 => "lightsalmon3a",
        138 => "rosybrown",
        139 => "grey63",
        140 => "mediumpurple2b",
        141 => "mediumpurple1",
        142 => "gold3a",
        143 => "darkkhaki",
        144 => "navajowhite3",
        145 => "grey69",
        146 => "lightsteelblue3",
        147 => "lightsteelblue",
        148 => "yellow3a",
        149 => "darkolivegreen3c",
        150 => "darkseagreen3b",
        151 => "darkseagreen2a",
        152 => "lightcyan3",
        153 => "lightskyblue1",
        154 => "greenyellow",
        155 => "darkolivegreen2",
        156 => "palegreen1b",
        157 => "darkseagreen2b",
        158 => "darkseagreen1a",
        159 => "paleturquoise1",
        160 => "red3b",
        161 => "deeppink3a",
        162 => "deeppink3b",
        163 => "magenta3a",
        164 => "magenta3b",
        165 => "magenta2a",
        166 => "darkorange3b",
        167 => "indianredb",
        168 => "hotpink3b",
        169 => "hotpink2",
        170 => "orchid",
        171 => "mediumorchid1a",
        172 => "orange3",
        173 => "lightsalmon3b",
        174 => "lightpink3",
        175 => "pink3",
        176 => "plum3",
        177 => "violet",
        178 => "gold3b",
        179 => "lightgoldenrod3",
        180 => "tan",
        181 => "mistyrose3",
        182 => "thistle3",
        183 => "plum2",
        184 => "yellow3b",
        185 => "khaki3",
        186 => "lightgoldenrod2",
        187 => "lightyellow3",
        188 => "grey84",
        189 => "lightsteelblue1",
        190 => "yellow2",
        191 => "darkolivegreen1a",
        192 => "darkolivegreen1b",
        193 => "darkseagreen1b",
        194 => "honeydew2",
        195 => "lightcyan1",
        196 => "red1",
        197 => "deeppink2",
        198 => "deeppink1a",
        199 => "deeppink1b",
        200 => "magenta2b",
        201 => "magenta1",
        202 => "orangered1",
        203 => "indianred1a",
        204 => "indianred1b",
        205 => "hotpinka",
        206 => "hotpinkb",
        207 => "mediumorchid1b",
        208 => "darkorange",
        209 => "salmon1",
        210 => "lightcoral",
        211 => "palevioletred1",
        212 => "orchid2",
        213 => "orchid1",
        214 => "orange1",
        215 => "sandybrown",
        216 => "lightsalmon1",
        217 => "lightpink1",
        218 => "pink1",
        219 => "plum1",
        220 => "gold1",
        221 => "lightgoldenrod2a",
        222 => "lightgoldenrod2b",
        223 => "navajowhite1",
        224 => "mistyrose1",
        225 => "thistle1",
        226 => "yellow1",
        227 => "lightgoldenrod1",
        228 => "khaki1",
        229 => "wheat1",
        230 => "cornsilk1",
        231 => "grey100",
        232 => "grey3",
        233 => "grey7",
        234 => "grey11",
        235 => "grey15",
        236 => "grey19",
        237 => "grey23",
        238 => "grey27",
        239 => "grey30",
        240 => "grey35",
        241 => "grey39",
        242 => "grey42",
        243 => "grey46",
        244 => "grey50",
        245 => "grey54",
        246 => "grey58",
        247 => "grey62",
        248 => "grey66",
        249 => "grey70",
        250 => "grey74",
        251 => "grey78",
        252 => "grey82",
        253 => "grey85",
        254 => "grey89",
        255 => "grey93",
    }
}
